config/routes.rb
Rails.application.routes.draw do
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/mytask/open',  to: 'mytask#my_open_tasks'
  get '/mytask/completed',  to: 'mytask#my_completed_tasks'
  resources :projects do
    resources :lists,          only: [:index, :show, :create, :destroy] do
      resources :items,          only: [:index, :show, :create, :destroy, :update] do
        resources :subtask,          only: [:show, :create, :destroy]
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'projects#index'
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :project
  has_many :items, dependent: :destroy
  validates :project_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }

  scope :get_list, -> (id) { where(id: id) }
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # Allow only if there is a current user
  before_action :set_project, only: [:index, :show, :create, :destroy]
  before_action :get_list, only: [:show, :destroy]

  def index
    @lists = @project.lists
    @list = @project.lists.build
  end

  def show
    # Scope list
    
    redirect_to project_list_items_path(@project, @list)
  end

  def create
    @list = @project.lists.build(list_params)
    if @list.save
      flash[:success] = "List created!"
      redirect_to project_list_url(@project, @list)
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to project_url(@project), notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    # pp params[:list][:project_id]
    @project = current_user.projects.get_project(params[:project_id]).first
    if @project.nil?
      redirect_to root_path
    end
  end
    # Never trust parameters from the scary internet, only allow the white list through.
  def list_params
    params.require(:list).permit(:name)
  end

  def get_list
    @list = @project.lists.get_list(params[:id]).first
    if @list.nil?
      redirect_to project_lists_path(@project)
    end
  end
end
  

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_list.html.erb
<li id="list-<%= list.id %>">
  <span class="name"><%= list.name %></span>
</li>

app/views/lists/_new.html.erb
<%= form_for [@project, @list] do |f| %>
  <div class="field">
    <%= f.text_field :name, placeholder: "Create new list" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project Name:</strong>
  <%= @project.name %>
</p>
<%= link_to 'Back', projects_path %>
</br>
</br>

<strong>Create list:</strong>
<div class="stats">
<%= render 'lists/new' %>
</div>

<div class="col-md-8">
<% if @project.lists.any? %>
  <h2>Lists (<%= @project.lists.count %>)</h2>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @lists.each do |list| %>
        <% if list.id? %>
          <tr>
            <td><%= list.name %></td>
            <td><%= link_to 'show', project_list_path(@project, list) %></td>
            <td><%= link_to "delete", [@project, list],
            :method => :delete, :confirm => "Really?" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

<% end %>
</div>