config/routes.rb
Rails.application.routes.draw do
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/mytask/open',  to: 'mytask#my_open_tasks'
  get '/mytask/completed',  to: 'mytask#my_completed_tasks'
  resources :projects do
    resources :lists,          only: [:index, :show, :create, :destroy] do
      resources :items,          only: [:index, :show, :create, :destroy, :update] do
        resources :subtask,          only: [:show, :create, :destroy]
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'projects#index'
end

app/controllers/mytask_controller.rb
class MytaskController < ApplicationController
  before_action :get_projects, only: [:my_open_tasks, :my_completed_tasks]

  def all_project_ids
    self.projects.pluck(:id)
  end

  def my_open_tasks
    # Filter in db
    if logged_in?
      user = current_user
      @items = current_user.all_visible_items.mytask(user)
      users = User.where("id in (#{@items.select(:assignees).distinct.to_sql})")
      @users = Hash[users.collect { |user| [user.id, user] } ]
    else
      redirect_to login_path
    end
  end

  def my_completed_tasks
    if logged_in?
      user = current_user
      @completed_items = current_user.all_visible_items.completed_task(user)
      users = User.where("id in (#{@completed_items.select(:assignees).distinct.to_sql})")
      @users = Hash[users.collect { |user| [user.id, user] } ]
    else
      redirect_to login_path
    end
  end

  private
  def get_projects
    # pp params[:list][:project_id]
    @projects = current_user.projects
  end
end

app/helpers/mytask_helper.rb
module MytaskHelper
end

app/views/mytask/my_completed_tasks.html.erb
<br>
<%= link_to 'Show open task', mytask_open_path %>
<br>
<%= link_to 'Back', root_path %>
<br>
<h1>Completed Tasks</h1>

<table style="width: 500px;">
  <thead>
    <tr>
      <th>Task</th>
      <th>Assignee</th>
      <th>Estimation</th>
    </tr>
  </thead>

  <tbody>
    <% @completed_items.each do |item| %>
      <tr>
        <td><%= item.content %></td>
        <td><%= @users[item.assignees.to_i].name %></td>
        <td><%= item.estimate %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/mytask/my_open_tasks.html.erb
<p id="notice"><%= notice %></p>

<br>
<%= link_to 'Show completed task', mytask_completed_path %>
<br>
<%= link_to 'Back', root_path %>
<br>

<h1>My Tasks</h1>

<table style="width: 500px;">
  <thead>
    <tr>
      <th>Task</th>
      <th>Assignee</th>
      <th>Estimation</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.content %></td>
        <td><%= @users[item.assignees.to_i].name %></td>
        <td><%= item.estimate %></td>
      </tr>
    <% end %>
  </tbody>
</table>